version: '3.8'

networks:
  replicanet:
    driver: bridge

services:
  # MySQL Master/Source Server
  mysql-source:
    image: mysql/mysql-server:5.7
    container_name: mysql-source
    hostname: source
    networks:
      - replicanet
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: testdb
    command: >
      --server-id=10
      --log-bin=mysql-bin-1.log
      --relay_log_info_repository=TABLE
      --master-info-repository=TABLE
      --gtid-mode=ON
      --log-slave-updates=ON
      --enforce-gtid-consistency
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pmypass"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"

  # MySQL Replica 1
  mysql-replica1:
    image: mysql/mysql-server:5.7
    container_name: mysql-replica1
    hostname: replica1
    networks:
      - replicanet
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    command: >
      --server-id=20
      --log-bin=mysql-bin-1.log
      --relay_log_info_repository=TABLE
      --master-info-repository=TABLE
      --gtid-mode=ON
      --log-slave-updates=ON
      --enforce-gtid-consistency
      --read-only
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pmypass"]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    depends_on:
      - mysql-source

  # MySQL Replica 2
  mysql-replica2:
    image: mysql/mysql-server:5.7
    container_name: mysql-replica2
    hostname: replica2
    networks:
      - replicanet
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    command: >
      --server-id=30
      --log-bin=mysql-bin-1.log
      --relay_log_info_repository=TABLE
      --master-info-repository=TABLE
      --gtid-mode=ON
      --log-slave-updates=ON
      --enforce-gtid-consistency
      --read-only
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pmypass"]
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306"
    depends_on:
      - mysql-source

  # ProxySQL
  proxysql:
    image: proxysql/proxysql:2.5.5
    container_name: proxysql
    hostname: proxysql
    networks:
      - replicanet
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    healthcheck:
      test: ["CMD", "proxysql_admin", "-u", "admin", "-padmin", "-h", "127.0.0.1", "-P", "6032", "--execute", "SELECT 1"]
      timeout: 20s
      retries: 5
    ports:
      - "6032:6032"  # Admin interface
      - "6033:6033"  # MySQL interface
    depends_on:
      - mysql-source
      - mysql-replica1
      - mysql-replica2

  # FastAPI Application
  fastapi-app:
    build: .
    container_name: fastapi-crud-app
    networks:
      - replicanet
    environment:
      DB_HOST: proxysql
      DB_PORT: 6033
      DB_USER: root
      DB_PASSWORD: mypass
      DB_NAME: testdb
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - proxysql
    volumes:
      - .:/app
    restart: unless-stopped